disabled_rules: # rule identifiers to exclude from running
  - comma
  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping
  - convenience_type
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - private_action
  - private_outlet
  - toggle_bool
  - unused_private_declaration
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - unavaialble_function
  - overridden_super_call
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - VABuildScript_PodInstallation
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 120
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
cyclomatic_complexity:
  warning: 15
  error: 20
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
